apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-prod-gw-envoy
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: prod-gw
  podMetricsEndpoints:
    - targetPort: 15090
      path: /stats/prometheus
      interval: 30s
