apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: service-app
spec:
  template:
    metadata:
      labels:
        role: service-app # 서비스 파드들이 이 라벨을 보고 노드를 요청할 것임
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2c"]
      nodeClassRef:
        group: karpenter.k8s.aws # v1에서는 group, kind 명시 권장
        kind: EC2NodeClass
        name: default
  limits:
    cpu: "100"      # 최대 CPU 코어 수 제한
    memory: 400Gi   # 최대 메모리 제한
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m